controller_manager:
  ros__parameters:
    update_rate: 20 # Hz

    speedy_base_control:
      type: diff_drive_controller/DiffDriveController

    scara_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    gripper_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

/**/scara_controller:
  ros__parameters:
    joints:
      - scara_revolute_arm_1_joint
      - scara_revolute_arm_2_joint
      - scara_prismatic_joint
      - scara_wrist_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true
    
/**/gripper_controller:
  ros__parameters:
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    allow_nonzero_velocity_at_trajectory_end: true

/**/speedy_base_control:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    use_sim_time: true
    publish_rate: 50.0
    left_wheel_names: ["front_left_wheel_joint","mid_left_wheel_joint","back_left_wheel_joint"]
    right_wheel_names: ["front_right_wheel_joint","mid_right_wheel_joint","back_right_wheel_joint"]
    wheel_separation: 1.700428
    wheel_radius: 0.39
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: -1.0
    right_wheel_radius_multiplier: 1.0
    # Base frame_id
    base_frame_id: base_footprint
    # odom tf will be published by direct laser odometry
    enable_odom_tf: true
    # Publish limited velocity
    publish_limited_velocity: true
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 3.0
        has_acceleration_limits: true
        max_acceleration: 3.0
