# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
use_sim_time: true

moveit_simple_controller_manager:
  controller_names:
    - scara_controller
    - gripper_controller

  scara_controller:
    type: FollowJointTrajectory
    joints:
      - scara_revolute_arm_1_joint
      - scara_revolute_arm_2_joint
      - scara_prismatic_joint
      - scara_wrist_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true
  gripper_controller:
    type: FollowJointTrajectory
    joints:
      - left_gripper_finger_joint
      - right_gripper_finger_joint
    action_ns: follow_joint_trajectory
    default: true
    use_sim_time: true